services:
  app:
    image: openjdk:17
    container_name: javalin-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    working_dir: /app
    restart: always
    command: ["java", "-jar", "target/javalin-demo-app-1.0-SNAPSHOT.jar"]
